# Generated by Django 2.0.3 on 2018-03-27 20:23

from django.db import migrations, models
import django.db.models.deletion
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20161014_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(choices=[('text', 'Text'), ('float', 'Float'), ('int', 'Integer'), ('date', 'Date'), ('bool', 'True / False'), ('object', 'Django Object'), ('enum', 'Multiple Choice')], max_length=6, verbose_name='data type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='enum_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eav.EnumGroup', verbose_name='choice group'),
        ),
        migrations.AlterField(
            model_name='value',
            name='generic_value_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_values', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value_enum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eav_values', to='eav.EnumValue'),
        ),
    ]
